# Generated by Django 5.1.3 on 2024-12-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='4-значный код подтверждения для регистрации.', max_length=4, null=True, verbose_name='код подтверждения'),
        ),
    ]
