# Generated by Django 5.1.3 on 2024-12-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorization', '0005_alter_clientuser_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='autorization.clientuser'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='referred_clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer', to='autorization.clientuser'),
        ),
    ]
