# Generated by Django 5.1.3 on 2024-12-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorization', '0006_clientuser_referred_by_clientuser_referred_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='referred_clients',
        ),
    ]
